#!/bin/bash
if [ $# -ne 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [samba] [backup]"
	/show/usageDescription "Copy a configuration to /etc/samba/smb.conf"
	/show/usage "$0 file"
	/show/example "$0 /user/config/samba.conf"
else
	settings=$1
		if [ -e $settings ];then
			/show/description "[SAMBA] $settings -> /etc/samba/smb.conf"
			/pi/syncFile /etc/samba/smb.conf
			cp -v $settings /etc/samba/smb.conf
			/pi/name
		else
			/show/listecho "$settings doesn't exists" $ERR
		fi
fi
