#!/bin/bash

if [ $# -eq 3 ]
then
	username=$1
	repo=$2
	sambaconf=$3
	/show/description "Downloading samba configuration $username/$repo/$sambaconf"

	/show/messagebox "Check Prerequisites"
	/system/install samba

	/show/messagebox "Replacing /etc/samba/smb.conf"
	/system/autoBackup "/etc/samba/smb.conf"
	/system/downloadGithubFileCustom "$username" "$repo" "$sambaconf" "/etc/samba/smb.conf"
	/do/samba/rename

/show/console
cat /etc/samba/smb.conf
/show/console

else
	/show/errorBox "Wrong arguments"
	/show/usage "sambaDownloadCustom username repo file"
	/show/example "sambaDownloadCustom pigetnet smb piget"
fi

