#!/bin/bash
description "Securing Samba with a global password"
description "Check Prerequisites"
installer samba-common-bin
installer samba
replaceLine "/etc/samba/smb.conf" "security" "        security = share" "\[global\]"
console
cat /etc/samba/smb.conf
console
restarter samba
