#!/bin/bash
description "Backup file sharing configuration to /boot/bootstrap/config/smb.conf"
cp -v /etc/samba/smb.conf /boot/bootstrap/config/smb.conf
console
cat /boot/bootstrap/config/smb.conf
console
