#!/bin/bash
description "Backup file sharing configuration to /boot/piget/config/smb.conf"
messagebox "Check Prerequisites"
installer samba
installer smbclient

cp -v /etc/samba/smb.conf /boot/piget/config/smb.conf
console
cat /boot/piget/config/smb.conf
console
