#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [samba] [variable]"
	/show/usageDescription "Check if samba shares something"
	/show/usage "$0"
	/show/return "0: share is active 1:Share is not active"
else
	checkConfig=$(cat /etc/samba/smb.conf |grep "path"|wc -l)

	if [ $checkConfig -eq 0 ];then
		echo "1"
	else
		echo "0"
	fi
fi
