#!/bin/bash
# If no arguments is provided we check if it was set inside bootstrap
/show/description "Hiding share"

if [ -f /boot/piget/config/name.txt ]
	then
		/show/messagebox "BOOTSTRAP CONFIGURATION FOUNDED"
		NEW_HOSTNAME=$(cat /boot/piget/config/name.txt)
	else
		/show/errorBox "No enough Arguments and no configuration inside /boot/piget/config/name.txt"
		/show/usage "PiNameMe newname"
		/show/example "PiNameMe raspberrypi"
		exit 1
fi


#Convert Name to Netbios convention to ensure compatibility
#If no hostname was provided will be reset to default (raspberrypi)
. /string/ToNetbios "$NEW_HOSTNAME"
NEW_HOSTNAME=$NewString

/do/samba/save
/net/resetSamba "$NEW_HOSTNAME"
