#!/bin/bash
# If no arguments is provided we check if it was set inside bootstrap
/show/description "Hiding share"

#Check if samba is not already in name mode only so it will not overwritten backup configuration
isNeeded=$(grep -v -F -x -f /do/samba/default/name /etc/samba/smb.conf|wc -l)

if [ $isNeeded -eq 1 ] 
	then
			/show/listecho "Already done"
else
	if [ -f /boot/piget/config/name.txt ]
		then
				/show/messagebox "BOOTSTRAP CONFIGURATION FOUNDED"
				NEW_HOSTNAME=$(cat /boot/piget/config/name.txt)
		else
				/show/errorBox "No enough Arguments and no configuration inside /boot/piget/config/name.txt"
				/show/usage "PiNameMe newname"
				/show/example "PiNameMe raspberrypi"
				exit 1
	fi
	#Convert Name to Netbios convention to ensure compatibility
	#If no hostname was provided will be reset to default (raspberrypi)
	. /string/ToNetbios "$NEW_HOSTNAME"
	NEW_HOSTNAME=$NewString

	#Backup current configuration, type /do/samba/load to reload file sharing
	/do/samba/save
	/net/resetSamba "$NEW_HOSTNAME"
fi
