#!/bin/bash
/system/install samba-common-bin

if [ $# -eq 1 ]
then

/show/messagebox "Check Prerequisites"
/system/install samba
/system/install smbclient

username=$1
smbpasswd -a $username
	if [ $? == 1 ]
	then
		/show/colecho "The user must exists on the system!" $ERR
	else
	/system/restart samba
	fi
else
	/show/errorBox "Wrong Arguments"
	/show/usage "sambaPassword username"
	/show/example "sambaPassword root" 
fi
