#!/bin/bash
# Source: http://stackoverflow.com/questions/12009/piping-password-to-smbpasswd
if [ $# -ge 3 ] || [ $# -eq 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [smbpasswd]"
	/show/usageDescription "Change password for an user or by default pi"
	/show/usage "$0 password or $0 username password"
	/show/example "$0 badPassword or $0 pi badPassword"
else
	username=pi
	password=raspberry
	if [ $# -eq 2 ];then
		username=$1
		password=$2
	else
		if [ $# -eq 1 ];then
		password=$1
		fi
	fi

	/show/description "[SAMBA] $username : PASSWORD"

	echo -ne "$password\n$password\n" | smbpasswd -a -s $username
	if [ $? -eq 1 ];then
		/show/listecho "The user must exists on the system!" $ERR
		sambaUsers=$(/do/samba/listUsers)
		if [ -e $sambaUsers ];then
			/show/listecho "no Samba users" $ERR
			echo "List of system users"
			/show/console
			/show/listUsers
			/show/console
		fi
	else
		/pi/name
		/show/listecho "Password changed" $OK
	fi
fi
