#!/bin/bash

# If no arguments is provided we check if it was set inside bootstrap


if [ $# -eq 0 ]
then
	if [ -f /boot/piget/config/name.txt ]
	then
		NEW_HOSTNAME=$(cat /boot/piget/config/name.txt)
		/show/description "Samba : $NEW_HOSTNAME"
		/show/listecho "Name ==> /boot/config/name.txt" $INFO

		/string/replaceLine "/etc/samba/smb.conf" "netbios name =" "        netbios name = $NEW_HOSTNAME" "\[global\]"
		/system/restart samba

	else
		/show/errorBox "No enough Arguments and no configuration inside /boot/piget/config/name.txt"
		/show/usage "sambaRename newname"
		/show/example "sambaRename raspberrypi"
		exit 1
	fi
fi

#If an arguments is provided we will use it
if [ $# -eq 1 ]
then
	NEW_HOSTNAME=$1
	echo $NEW_HOSTNAME > /boot/piget/config/name.txt
	/pi/rename
fi
