#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[release] [samba] [service]"
	/show/usageDescription "Restart samba services"
	/show/usage "$0"
else
	/system/restart samba
fi