#!/bin/bash

if [ $# -eq 3 ]
then
	username=$1
	repo=$2
	sambaconf=$3
	description "Downloading samba configuration $username/$repo/$sambaconf"

	messagebox "Check Prerequisites"
	installer samba

	messagebox "Replacing /etc/samba/smb.conf"
	autoBackup "/etc/samba/smb.conf"
	. downloadFileCustom "$username" "$repo" "$sambaconf" "/etc/samba/smb.conf"
	sambaRename

console
cat /etc/samba/smb.conf
console

else
	errorBox "Wrong arguments"
	usage "sambaDownloadCustom username repo file"
	example "sambaDownloadCustom pigetnet smb piget"
fi

