#!/bin/bash
installer samba-common-bin

if [ $# -eq 1 ]
then

messagebox "Check Prerequisites"
installer samba
installer smbclient

username=$1
smbpasswd -a $username
	if [ $? == 1 ]
	then
		colecho "The user must exists on the system!" $ERR
	else
	restarter samba
	fi
else
errorBox "Wrong Arguments"
usage "sambaPassword username"
example "sambaPassword root" 
fi
