#!/bin/bash
description "Securing Samba with a global password"

messagebox "Check Prerequisites"
installer samba
installer smbclient

messagebox "User List"
sambaUsers=$(sambaListUsers)
if [ -e $sambaUsers ]
then
	nlbecho "no Samba users" $WARN;minibox_WARNING
	echo "List of system users"
	console
	listUsers
	console
	. askUser "User"
	smbpasswd -a $USERANSWER
	echo $USERANSWER
fi
replaceLine "/etc/samba/smb.conf" "security" "        security = user" "\[global\]"
console
cat /etc/samba/smb.conf
console
sambaRestart
