#!/bin/bash
description "Public sharing (USE ONLY ON YOUR OWN NETWORK)"

description "Check Prerequisites"
installer samba
installer smbclient

replaceLine "/etc/samba/smb.conf" "security" "        security = share" "\[global\]"
console
cat /etc/samba/smb.conf
console
restarter samba
