#!/bin/bash

if [ $# -eq 1 ]
then
	description "Downloading samba configuration $1"
	sambaconf=$1

	messagebox "Check Prerequisites"
	installer samba

	messagebox "Replacing /etc/samba/smb.conf"
	autoBackup "/etc/samba/smb.conf"
	. downloadFile "smb" "$sambaconf" "/etc/samba/smb.conf"
	sambaRename

console
cat /etc/samba/smb.conf
console

else
	errorBox "Wrong arguments"
	usage "sambaDownload dir"
	example "sambaDownload pigetdev"
fi

