#!/bin/bash
if [ $# -ge 3 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [smbpasswd] [interactive]"
	/show/usageDescription "Change password for an user or by default pi (interactive)"
	/show/usage "$0 password or $0 username password"
	/show/example "$0 raspberry or $0 pi raspberry"
else
	username=pi
	if [ $# -eq 1 ];then
		username=$1
	fi


	/show/description "[SAMBA] $username : PASSWORD"
	smbpasswd -a $username
	if [ $? == 1 ]
		then
			/show/listecho "The user must exists on the system!" $ERR
			sambaUsers=$(/do/samba/listUsers)
			if [ -e $sambaUsers ];then
				/show/listecho "no Samba users" $ERR
				echo "List of system users"
				/show/console
				/show/listUsers
				/show/console
			fi
		else
			/do/samba/secure
			/show/listecho "Password changed" $OK
		fi
fi
