#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [samba] [share]"
	/show/usageDescription "Share nothing but keep netbios name (will do nothing if this is already the case)"
	/show/usage "$0"
	/show/example "$0"
else
	/show/description "[SAMBA] - Share nothing"

	#Check if samba is not already in name mode only so it will not overwritten backup configuration
	isNeeded=$(grep -v -F -x -f /do/samba/conf/name /etc/samba/smb.conf|wc -l)

	if [ $isNeeded -eq 1 ] 
		then
				/show/listecho "Already done" $OK
	else
		#!/bin/bash
		sambaName=$(/show/smbGetName)
		cp /do/samba/conf/name /etc/samba/smb.conf
		/pi/name $sambaName
	fi
fi
