#!/bin/bash
sambaName=$(/show/smbGetName)
/show/description "[SAMBA] share Piget Folders"
/show/listecho "\\\\$sambaName\piget --> Modules" $OK
/show/listecho "\\\\$sambaName\user --> User" $WARN
/show/listecho "\\\\$sambaName\boot --> SD card" $ERR
cp /do/samba/conf/piget /etc/samba/smb.conf
/pi/name