#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [samba] [smbstatus] [boolean] [return]"
	/show/usageDescription "Show if a user is connected to samba share"
	/show/usage "$0"
	/show/return "0: no users connected, 1: users connected"

else
	status=$(smbstatus|grep "Locked files:"|tail -n 1)

	if [[ $status == "Locked files:" ]];then
		echo "1"
	else	
		echo "0"
	fi
fi